#pragma once
#include <winerror.h>

constexpr HRESULT E_BACKBUFFER_FAILED        = MAKE_HRESULT(1, FACILITY_NULL, 0x201);
constexpr HRESULT E_FFMPEG_CONTEXT_FAILED    = MAKE_HRESULT(1, FACILITY_NULL, 0x202);
constexpr HRESULT E_FFMPEG_STREAM_FAILED     = MAKE_HRESULT(1, FACILITY_NULL, 0x203);
constexpr HRESULT E_FFMPEG_CODEC_NOT_FOUND   = MAKE_HRESULT(1, FACILITY_NULL, 0x204);
constexpr HRESULT E_FFMPEG_CODEC_ALLOC_FAILED= MAKE_HRESULT(1, FACILITY_NULL, 0x205);
constexpr HRESULT E_FFMPEG_CODEC_OPEN_FAILED = MAKE_HRESULT(1, FACILITY_NULL, 0x206);
constexpr HRESULT E_FFMPEG_FILE_OPEN_FAILED  = MAKE_HRESULT(1, FACILITY_NULL, 0x207);
constexpr HRESULT E_FFMPEG_HEADER_WRITE_FAILED = MAKE_HRESULT(1, FACILITY_NULL, 0x208);
constexpr HRESULT E_FFMPEG_FRAME_ALLOC_FAILED= MAKE_HRESULT(1, FACILITY_NULL, 0x209);
constexpr HRESULT E_FFMPEG_INIT_FAILED       = MAKE_HRESULT(1, FACILITY_NULL, 0x20A);
